name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip sync --system requirements.lock
      - name: Ruff - Format check
        run: ruff format --check .
      - name: Ruff - Lint
        run: ruff check .
      - name: Mypy - Type check
        run: mypy .
      - name: Test with pytest
        run: pytest

      - name: Check code coverage
        run: pytest --cov=src --cov-fail-under=90

      - name: Check architecture dependencies
        run: lint-imports

      - name: Detect-secrets - Security scan
        run: detect-secrets scan --baseline .secrets.baseline
      - name: Bandit - Security linting
        run: bandit -r src/ -f json
